### PR TITLE
Add Kraab as an entity

### PR DESCRIPTION
**Pull request by vemerion**
kraab

This pull request adds the Ben 10 enemy Kraab as an entity.

### What this pull request contains
* KraabEntity/KraabRenderer/KraabModel: The classes that make up the entity
* KraabBoltEntity: A projectile entity that Kraab occasionally shoots at nearby players

### What this pull request does not contain
* To avoid having to make a bunch of small changes/additions, I did not add a spawn egg for Kraab, and I did not add a translation name either. Currently Kraab can only spawn via the /summon command
* I did not add any item drop when Kraab is killed
* I did not add any sounds to Kraab

### CODE REVIEW

**Comment by RealYusufIsmail** [comment]
Do you have discord so i can contact you

**Comment by RealYusufIsmail** [comment]
You can add a spawn egg if you want. I will add the translation name

**Comment by vemerion** [comment]
Sure, my discord is vemerion#0689

**Comment by RealYusufIsmail** [comment]
Your discord is wrong its 4 digets

**Pull request merged**
